#pragma config(Sensor, S3,     light,          sensorLightActive)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//2550 for one square

void action(char* direction, int speed, int del, bool angle, char* material){
	if (direction == "r"){
		motor[motorB] = -speed;
		motor[motorC] = speed;
	}
	else if (direction == "l"){
		motor[motorB] = speed;
		motor[motorC] = -speed;
	}
	else if (direction == "s"){
		motor[motorB] = speed;
		motor[motorC] = speed;
	}
	else if (direction == "b"){
		motor[motorB] = -speed;
		motor[motorC] = -speed;
	}

	if (angle == true){
		if (material == "mat") {
			delay(del * 3.8); // placeholder
		}
		else if (material == "table"
			delay(del * 3.55);
		}
		else if (material == "wood") {
			delay(del * 4); // placeholder
		}
	}

	else if (angle == false){
		delay(del);
	}

	motor[motorB] = 0;
	motor[motorC] = 0;
	delay(200);
}

task main(){
	action("s", 50, 5000, false, "wood");
	action("r", 50, 45, true, "wood");
	action("s", 50, 1000, false, "wood");
	action("r", 50, 55, true, "wood");
	action("s", 50, 700, false, "wood");
	action("r", 50, 90, true, "wood");
	action("s", 50, 700, false, "wood");
	action("l", 50, 100, true, "wood");
}
